"""
DataMind — ActionAgent
Converts InsightAgent outputs into autonomous actions:
  - Reorder alerts
  - Executive PDF/Markdown reports
  - Slack/email alert payloads
  - Dashboard refresh triggers

This closes the loop: raw data → insight → autonomous action
"""

import json
import datetime
from pathlib import Path
import sys
sys.path.append(str(Path(__file__).resolve().parents[2]))

from src.agents.base_agent import BaseAgent, AgentRole, A2AMessage


REPORTS_DIR = Path(__file__).resolve().parents[3] / "data" / "reports"
REPORTS_DIR.mkdir(parents=True, exist_ok=True)


class ActionAgent(BaseAgent):
    """
    Terminal agent — converts insights into concrete, persisted actions.
    All actions are idempotent and logged.
    """

    def __init__(self):
        super().__init__(role=AgentRole.ACTION)
        self._action_log: list = []

    def _execute(self, message: A2AMessage) -> dict:
        intent  = message.intent
        payload = message.payload

        if intent == "reorder_alert":
            return self._generate_reorder_alerts(payload)
        if intent == "executive_report":
            return self._generate_executive_report(payload)
        if intent == "anomaly_alert":
            return self._generate_anomaly_alert(payload)
        if intent == "forecast_report":
            return self._generate_forecast_report(payload)

        raise ValueError(f"Unknown action intent: {intent}")

    # ── Reorder Alerts ────────────────────────────────────────────────────────
    def _generate_reorder_alerts(self, payload: dict) -> dict:
        reorder_data = payload.get("data_result", {}).get("data", [])
        insight      = payload.get("insight", {})

        alerts = []
        for row in reorder_data:
            alerts.append({
                "type"       : "REORDER_REQUIRED",
                "product"    : row.get("description", "Unknown"),
                "stock_code" : row.get("stock_code", ""),
                "change_pct" : row.get("unit_change_pct", 0),
                "urgency"    : "HIGH" if row.get("unit_change_pct", 0) < -40 else "MEDIUM",
                "message"    : (
                    f"⚠️  REORDER ALERT: '{row.get('description', '')}' sales dropped "
                    f"{abs(row.get('unit_change_pct', 0)):.1f}% vs prior period. "
                    f"Immediate restocking recommended."
                ),
                "generated_at": datetime.datetime.now().isoformat(),
            })

        # Save alerts as JSON
        alert_path = REPORTS_DIR / f"reorder_alerts_{datetime.date.today()}.json"
        with open(alert_path, "w", encoding="utf-8") as f:
            json.dump(alerts, f, indent=2, default=str)

        self._action_log.append({"action": "reorder_alert", "count": len(alerts),
                                  "path": str(alert_path)})
        self.log.info(f"Generated {len(alerts)} reorder alerts → {alert_path}")

        return {
            "action"     : "reorder_alerts",
            "alert_count": len(alerts),
            "high_urgency": sum(1 for a in alerts if a["urgency"] == "HIGH"),
            "alerts"     : alerts[:5],   # return top 5
            "saved_to"   : str(alert_path),
        }

    # ── Executive Report ──────────────────────────────────────────────────────
    def _generate_executive_report(self, payload: dict) -> dict:
        insights    = payload.get("insights", {})
        forecast    = payload.get("forecast", {})
        now         = datetime.datetime.now()

        report_md   = f"""# DataMind Executive Report
Generated: {now.strftime("%Y-%m-%d %H:%M")}

---

## Revenue Analysis
{insights.get('narrative', 'No narrative available.')}

---

## Demand Forecast (Next {len(forecast.get('dates', []))} Days)
{forecast.get('narrative', 'Forecast not available.')}

| Date | Forecast (£) | Lower CI | Upper CI |
|------|-------------|----------|----------|
"""
        for i, d in enumerate(forecast.get("dates", [])):
            fc  = forecast.get("forecast", [])[i] if i < len(forecast.get("forecast", [])) else "—"
            lo  = forecast.get("lower_ci", [])[i] if i < len(forecast.get("lower_ci", [])) else "—"
            hi  = forecast.get("upper_ci", [])[i] if i < len(forecast.get("upper_ci", [])) else "—"
            report_md += f"| {d} | £{fc:,.2f} | £{lo:,.2f} | £{hi:,.2f} |\n" \
                         if isinstance(fc, (int, float)) else f"| {d} | {fc} | {lo} | {hi} |\n"

        report_md += "\n---\n*Report auto-generated by DataMind ActionAgent*\n"

        report_path = REPORTS_DIR / f"executive_report_{now.strftime('%Y%m%d_%H%M')}.md"
        with open(report_path, "w", encoding="utf-8") as f:
            f.write(report_md)

        self._action_log.append({"action": "executive_report", "path": str(report_path)})
        self.log.info(f"Executive report saved → {report_path}")

        return {
            "action"    : "executive_report",
            "saved_to"  : str(report_path),
            "word_count": len(report_md.split()),
            "preview"   : report_md[:300] + "...",
        }

    # ── Anomaly Alert ─────────────────────────────────────────────────────────
    def _generate_anomaly_alert(self, payload: dict) -> dict:
        data     = payload.get("data_result", {}).get("data", [])
        insight  = payload.get("insight", {})

        # Detect anomalies: MoM growth > ±50%
        anomalies = []
        for row in data:
            pct = row.get("mom_growth_pct", 0) or 0
            if abs(pct) > 50:
                anomalies.append({
                    "period"     : f"{row.get('month_name')} {row.get('year')}",
                    "growth_pct" : pct,
                    "revenue"    : row.get("revenue"),
                    "alert_type" : "SPIKE" if pct > 0 else "DROP",
                    "message"    : (
                        f"{'📈 SPIKE' if pct > 0 else '📉 DROP'}: "
                        f"{row.get('month_name')} {row.get('year')} showed "
                        f"{abs(pct):.1f}% {'growth' if pct > 0 else 'decline'} "
                        f"(£{row.get('revenue', 0):,.2f})"
                    ),
                })

        alert_path = REPORTS_DIR / f"anomaly_alerts_{datetime.date.today()}.json"
        with open(alert_path, "w", encoding="utf-8") as f:
            json.dump(anomalies, f, indent=2, default=str)

        return {
            "action"       : "anomaly_alert",
            "anomaly_count": len(anomalies),
            "anomalies"    : anomalies,
            "saved_to"     : str(alert_path),
        }

    # ── Forecast Report ───────────────────────────────────────────────────────
    def _generate_forecast_report(self, payload: dict) -> dict:
        forecast = payload.get("forecast", {})
        narrative = forecast.get("narrative", "")

        report = {
            "type"      : "demand_forecast",
            "generated" : datetime.datetime.now().isoformat(),
            "horizon"   : f"{len(forecast.get('dates', []))} days",
            "dates"     : forecast.get("dates", []),
            "forecast"  : forecast.get("forecast", []),
            "lower_ci"  : forecast.get("lower_ci", []),
            "upper_ci"  : forecast.get("upper_ci", []),
            "narrative" : narrative,
            "total_projected": sum(forecast.get("forecast", [])),
        }

        path = REPORTS_DIR / f"forecast_{datetime.date.today()}.json"
        with open(path, "w", encoding="utf-8") as f:
            json.dump(report, f, indent=2, default=str)

        return {"action": "forecast_report", "saved_to": str(path), "report": report}

    def get_action_log(self) -> list:
        return self._action_log
